### ISSUE TITLE
New: Work week

### ISSUE THREAD

**Issue by LuisRodriguezLD** [offset-dev/strapi-calendar#15]
I'd be nice to have a work-week (Mon-Fri) view

**Comment by austinwoodall** [comment]
I got this one! :D

**Comment by gganster** [comment]
Hi, Any news on this feature ? 
It would be nice to add a means to change start day. Like Monday->Sunday instead of Sunday->Saturday

**Comment by LuisRodriguezLD** [comment]
Hello @gganster, Austin has been busy with other projects.
I'll assign this issue to you, thanks for all the help

**Comment by LuisRodriguezLD** [comment]
Done since v0.1.0
