### ISSUE TITLE
New: Spanish Locale

### ISSUE THREAD

**Issue by LuisRodriguezLD** [offset-dev/strapi-calendar#16]
I'd be nice to have this plugin localized in Spanish

**Comment by Carababusha** [comment]
Hi @LuisRodriguezLD!

I can help with the translation if you'd still like to localize it into Spanish 😊

**Comment by LuisRodriguezLD** [comment]
Absolutely, I'll assign you this issue. Tag me whenever the PR is ready. Thank you!
