### ISSUE TITLE
Doesn't run under Node 18, breaks Strapi example app Foodadvisor

### ISSUE THREAD

**Issue by sonicviz** [offset-dev/strapi-calendar#19]
https://github.com/strapi/foodadvisor

Tried installing under Node 18.x
Even after updating strapi-calendar version from 0.0.8 to 0.0.9 it still fails

E:\Source Control\AI Apps\Back End\Strapi\foodadvisor\api>yarn && yarn seed && yarn develop
yarn install v1.21.1
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error @offset-dev/strapi-calendar@0.0.9: The engine "node" is incompatible with this module. Expected version ">=12.x.x <=16.x.x". Got "18.12.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation

**Comment by LuisRodriguezLD** [comment]
Fixed in #22
