### ISSUE TITLE
Backward/Forward button for month view

### ISSUE THREAD

**Issue by james6b** [offset-dev/strapi-calendar#2]
As a user, it would be nice to have buttons pre-programmed to be able to switch the month I'm looking at and not needing to manually select a month/day in the field in the upper left.

**Comment by LuisRodriguezLD** [comment]
that makes a lot of sense, I'll work on it

**Comment by LuisRodriguezLD** [comment]
@james6b done! please upgrade to v0.0.5

**Comment by james6b** [comment]
Thank you!
