### ISSUE TITLE
Different colors for different events

### ISSUE THREAD

**Issue by tellierflexus** [offset-dev/strapi-calendar#27]
Hello !
Thank you for developping this plugin. I come with a suggestion, it would be cool to be able to have different color for events depending on a field for example. 
Example the room reserved. The color will be different for each room. So if we have 2 events a the same time we see if there's really a conflict or not :)

**Comment by LuisRodriguezLD** [comment]
Hello @tellierflexus, the plugin already supports this (added [here](https://github.com/offset-dev/strapi-calendar/pull/21))
but yeah, I'm aware we need more docs on this.

I'll close this for now but let me know if you think we should reopen it.
