### ISSUE TITLE
Calendar settings disappeared from strapi dashboard

### ISSUE THREAD

**Issue by greeneyz** [offset-dev/strapi-calendar#31]
Calendar settings disappeared from strapi dashboard in localhost. The project is deployed and in production it is showing the calendar settings but in localhost it is not showing anymore although the plugin is installed.
Strapi version: 4.11

**Comment by LuisRodriguezLD** [comment]
Interesting behavior. 
I just tried it on an empty project and it works fine on my end.

Try updating the strapi version but it that doesn't work:
1. do you mean the menu link is not showing or the settings themselves?
2. can you access directly? eg `http://localhost:1337/admin/settings/calendar`
3. does your prod and local versions use the same db/config?
