### ISSUE TITLE
Issue with Strapi Calendar Package - Unable to View events for date and week in selected date range

### ISSUE THREAD

**Issue by vishalmenghare1** [offset-dev/strapi-calendar#40]
The strapi-calendar package seems to be experiencing issues when selecting different start and end dates for events. Specifically, when I select a range of dates for an event, the week view or day view doesn't display any events. It only seems to work for a single date. This behavior is inconsistent with the expected functionality of providing day-to-day or week-to-week views for events.

![MicrosoftTeams-image (19)](https://github.com/offset-dev/strapi-calendar/assets/114383282/47bfef21-0949-4157-af90-fa5c5af269e2)
![MicrosoftTeams-image (18)](https://github.com/offset-dev/strapi-calendar/assets/114383282/e114418a-ce40-46d9-94e7-9b5cdb4b692c)
![MicrosoftTeams-image (17)](https://github.com/offset-dev/strapi-calendar/assets/114383282/d1552a0e-719f-49ab-87c0-c82c5ca1d752)

**Comment by LuisRodriguezLD** [comment]
@vishalmenghare1 thanks for reporting this bug, I have a PR ready, could you spend five minutes just to make sure it solves the problem? #41

**Comment by LuisRodriguezLD** [comment]
Fixed in #41
