### ISSUE TITLE
Strapi 5

### ISSUE THREAD

**Issue by yevhenskakun** [offset-dev/strapi-calendar#42]
Do you plan to support strapi v5?

**Comment by LuisRodriguezLD** [comment]
**Absolutely**. 
I'll spend time this week making sure the plugin is fully compatible with v5. 
If you see any errors _please_ post them here so I can take a closer look.

**Comment by Antoine-360pixel** [comment]
Hi @LuisRodriguezLD , thks 

```bash
$ npm i @offset-dev/strapi-calendar@0.1.2
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ws-f-d-h-strapi@0.1.0
npm ERR! Found: react-router-dom@6.26.2
npm ERR! node_modules/react-router-dom
npm ERR!   react-router-dom@"^6.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-router-dom@"^5.3.4" from @offset-dev/strapi-calendar@0.1.2
npm ERR! node_modules/@offset-dev/strapi-calendar
npm ERR!   @offset-dev/strapi-calendar@"0.1.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by LuisRodriguezLD** [comment]
Hello!
I'll be launching v1-beta1 this week, please let me know if you interested in trying it out :) 

New features include:
- New Calendar Library
- Fully TS Support
- Strapi 5 compat
- New Strapi Plugin SDK
- Now using Document Service API

**Comment by Antoine-360pixel** [comment]
> Hello! I'll be launching v1-beta1 this week, please let me know if you interested in trying it out :)
> 
> New features include:
> 
> * New Calendar Library
> * Fully TS Support
> * Strapi 5 compat
> * New Strapi Plugin SDK
> * Now using Document Service API

Hello, yes please! Thanks

**Comment by LuisRodriguezLD** [comment]
Beta is live!

Please install using
`npm install @offset-dev/strapi-calendar@1.0.0-beta.1`

You may submit feedback by creating an issue with the tag `v1`

**Comment by LuisRodriguezLD** [comment]
[V1](https://www.npmjs.com/package/@offset-dev/strapi-calendar) has been deployed to NPM
