### ISSUE TITLE
Sugestion:  see the scheduled articles in the calendar 

### ISSUE THREAD

**Issue by leomunizq** [offset-dev/strapi-calendar#46]
if I'm using the scheduler plugin https://market.strapi.io/plugins/@webbio-strapi-plugin-scheduler, is there any way to see the scheduled articles in the calendar?

**Comment by schimini** [comment]
Hi @leomunizq ,

Can you check if this fits your needs? https://github.com/offset-dev/strapi-calendar/pull/20
I integrated with another scheduler but the feature within strapi-calendar should be plugin agnostic
