### ISSUE TITLE
Invalid Redirect URL when clicking on event.

### ISSUE THREAD

**Issue by BayBreezy** [offset-dev/strapi-calendar#48]
Hello, 

I noticed that in strapi v4.25.11, the URL constructed in the month view of the calender is not redirecting to the correct place.

From the month view, I can see an event. When i hover over the event, i see where it is redirecting to this URL:
`http://localhost:1337/admin/content-manager/collectionType/api::promotion.promotion/2`.

The correct path to get to this record is `http://localhost:1337/admin/content-manager/collection-types/api::promotion.promotion/2`

I am not sure if this was the path before a certain update.

Took a look at the code and this line seems to be where the issue is (I am no React expert lolol): https://github.com/offset-dev/strapi-calendar/blob/master/admin/src/pages/index.js#L331

**Comment by LuisRodriguezLD** [comment]
Hello, thanks for reporting!
This issue has been fixed in `develop` 
https://github.com/offset-dev/strapi-calendar/commit/50febc00ce4fc39904f10649e52c694741f05964

I can deploy a new minor version if this is urgent to you but I plan to remake this plugin from scratch now that Strapi 5 is out

**Comment by BayBreezy** [comment]
Oh cool cool. 
No, it's not urgent. I just wanted to point it out.
I can wait on the v5 version. I want to use v5 but all the plugins are behind(understandably) at this point.. All my apps need plugins lol

**Comment by LuisRodriguezLD** [comment]
Decided to still publish all changes since I'm starting a new major version.
https://www.npmjs.com/package/@offset-dev/strapi-calendar?activeTab=readme

**Comment by BayBreezy** [comment]
Thank you.
