### ISSUE TITLE
Module not found: Error: Can't resolve '@mui/x-date-pickers/AdapterMoment'

### ISSUE THREAD

**Issue by Developer-Nijat** [offset-dev/strapi-calendar#9]
![Capture](https://user-images.githubusercontent.com/51002164/179349982-7e34b71d-a670-40bf-ac3b-43c914a8972b.PNG)

STRAPI VERSION: v4.2.3
NODE VERSION: v16.13.1
@offset-dev/strapi-calendar: 0.0.7

**Solution**
run command in terminal
`yarn add @mui/x-date-pickers`
then build strapi project and start.

**Comment by nharpa** [comment]
+1 on experiencing this and solution above resolving.

**Comment by LuisRodriguezLD** [comment]
Interesting, thanks for coming up with a fix.
I recommend making a PR so everyone can benefit from it

**Comment by PrinceEntree8** [comment]
Hello,
I'm facing this issue with Strapi `v4.3.2` and `v0.0.7` of this module.
![image](https://user-images.githubusercontent.com/32601364/182650553-6df067fa-5ce8-45bc-85be-6c20dc6cb107.png)

Here are my `package.json`'s dependencies:
```
"devDependencies": {},
"dependencies": {
  "@_sh/strapi-plugin-ckeditor": "^1.1.1",
  "@offset-dev/strapi-calendar": "^0.0.7",
  "@strapi/plugin-graphql": "^4.3.0",
  "@strapi/plugin-i18n": "4.3.0",
  "@strapi/plugin-seo": "^1.7.4",
  "@strapi/plugin-users-permissions": "~4.3.0",
  "@strapi/strapi": "~4.3.0",
  "better-sqlite3": "7.4.6",
  "strapi-plugin-navigation": "^2.2.0"
},
```
